# Generated by Django 4.1.7 on 2023-03-29 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.AddField(
            model_name='action',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.company'),
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('aucun', 'None'), ('lead', 'Lead'), ('lead mort', 'Lead Dead'), ('prospect', 'Prospect'), ('prospect mort', 'Prospect Dead'), ('client', 'Client')], default='aucun', max_length=30),
        ),
    ]
