# Generated by Django 4.1.7 on 2023-03-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('aucun', 'None'), ('lead', 'Lead'), ('lead mort', 'Lead Dead'), ('prospect', 'Prospect'), ('prospect mort', 'Prospect Dead'), ('client', 'Client')], default='aucun', max_length=30),
        ),
    ]
