# Generated by Django 4.1.7 on 2023-03-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('Rappel', 'Reminder'), ('Appel', 'Call'), ('Email', 'Email'), ('Rendez-vous', 'Meeting'), ('Visite', 'Visit'), ('Autre', 'Other')], default='Autre', max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_at', models.DateTimeField()),
                ('done_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
