# Generated by Django 4.1.7 on 2023-04-03 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_remove_user_status_action_customer_customer_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='action', to='crm.customer'),
        ),
    ]
