# Generated by Django 4.1.7 on 2023-04-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_action_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='company',
        ),
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.ManyToManyField(blank=True, related_name='customers', to='crm.company'),
        ),
    ]
