# Generated by Django 4.1.7 on 2023-04-03 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_company_contacts_remove_customer_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='company',
        ),
    ]
