# Generated by Django 4.1.7 on 2023-04-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_alter_message_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('Rappel', 'Reminder'), ('Appel', 'Call'), ('Email', 'Email'), ('Rendez-vous', 'Meeting'), ('Visite', 'Visit'), ('Vente', 'Sale'), ('Autre', 'Other')], default='Autre', max_length=30),
        ),
    ]
